services:
  db:
    image: postgres:18
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: pv179
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: